### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not int

### ISSUE THREAD

**Issue by ZuyomiTee** [quasar098/limbos32#48]
Having issues with this. 

I run "server.py" and then I run "spawn-all", as indicated, but the terminal shows this:

![image](https://github.com/quasar098/limbos32/assets/80680390/3f6911dc-954a-4846-b189-1d4ebaee1e60)

Plaintext:
Traceback (most recent call last):
File "C:\Users\zuyom\Downloads\limbos32-master\main.py", line 81, in
font = pygame.font.SysFont("Arial", 20)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zuyom\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\sysfont.py", line 418, in SysFont
initsysfonts()
File "C:\Users\zuyom\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\sysfont.py", line 357, in initsysfonts
fonts = initsysfonts_win32()
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\zuyom\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\sysfont.py", line 82, in initsysfonts_win32
if splitext(font)[1].lower() not in OpenType_extensions:
^^^^^^^^^^^^^^
File "", line 258, in splitext
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by ZuyomiTee** [comment]
### Plaintext:

Traceback (most recent call last):
  File "C:\Users\zuyom\Downloads\limbos32-master\main.py", line 81, in <module>
    font = pygame.font.SysFont("Arial", 20)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zuyom\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\sysfont.py", line 418, in SysFont
    initsysfonts()
  File "C:\Users\zuyom\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\sysfont.py", line 357, in initsysfonts
    fonts = initsysfonts_win32()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zuyom\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygame\sysfont.py", line 82, in initsysfonts_win32
    if splitext(font)[1].lower() not in OpenType_extensions:
       ^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 258, in splitext
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by KablammoMan** [comment]
Looking at the stacktrace lead me to look through the PyGame and Python source code. I think (with ~80% certainty) that this means that there is a key in the windows registry that is supposed to store a font name (e.g. `times.ttf`), but instead contains the wrong content, possibly an integer based on the final error message, either in one of the 4 registry paths: `HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts`, `HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Fonts`, `HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts` or `HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Fonts`. I tried to find what happens in line 258 of the python os.path module but there is just a comment in the latest release, sorry I can't help much more. Hopefully someone else can debug further.

**Comment by ZuyomiTee** [comment]
Thank you for this analysis!

**Comment by quasar098** [comment]
woah yeah never seen that defo a pygame issue, not an issue with midi-playground. perhaps contact the guys that run pygame or pygame-ce projects
