### ISSUE TITLE
Getting Requirements to build wheel did not run successfully

### ISSUE THREAD

**Issue by ICrashWindows12** [quasar098/limbos32#83]
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      Skipping Cython compilation

      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.28.3-VC.zip 0d3af96d6745c1473f8eca305af53680365ea442
      Unzipping :prebuilt_downloads\SDL2-devel-2.28.3-VC.zip:
      Downloading... https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip 137f86474691f4e12e76e07d58d5920c8d844d5b
      Unzipping :prebuilt_downloads\SDL2_image-devel-2.0.5-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.20.1/SDL2_ttf-devel-2.20.1-VC.zip 371606aceba450384428fd2852f73d2f6290b136
      Unzipping :prebuilt_downloads\SDL2_ttf-devel-2.20.1-VC.zip:
      Downloading... https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.2/SDL2_mixer-devel-2.6.2-VC.zip 000e3ea8a50261d46dbd200fb450b93c59ed4482
      Unzipping :prebuilt_downloads\SDL2_mixer-devel-2.6.2-VC.zip:
      Downloading... https://github.com/pygame/pygame/releases/download/2.1.3.dev4/prebuilt-x64-pygame-2.1.4-20220319.zip 16b46596744ce9ef80e7e40fa72ddbafef1cf586
      Unzipping :prebuilt_downloads\prebuilt-x64-pygame-2.1.4-20220319.zip:
      copying into .\prebuilt-x64
      Path for SDL: prebuilt-x64\SDL2-2.28.3
      ...Library directory for SDL: prebuilt-x64/SDL2-2.28.3/lib/x64
      ...Include directory for SDL: prebuilt-x64/SDL2-2.28.3/include
      Path for FONT: prebuilt-x64\SDL2_ttf-2.20.1
      ...Library directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64
      ...Include directory for FONT: prebuilt-x64/SDL2_ttf-2.20.1/include
      Path for IMAGE: prebuilt-x64\SDL2_image-2.0.5
      ...Library directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/lib/x64
      ...Include directory for IMAGE: prebuilt-x64/SDL2_image-2.0.5/include
      Path for MIXER: prebuilt-x64\SDL2_mixer-2.6.2
      ...Library directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64
      ...Include directory for MIXER: prebuilt-x64/SDL2_mixer-2.6.2/include
      Path for PORTMIDI: prebuilt-x64
      ...Library directory for PORTMIDI: prebuilt-x64/lib
      ...Include directory for PORTMIDI: prebuilt-x64/include
      DLL for SDL2: prebuilt-x64/SDL2-2.28.3/lib/x64/SDL2.dll
      DLL for SDL2_ttf: prebuilt-x64/SDL2_ttf-2.20.1/lib/x64/SDL2_ttf.dll
      DLL for SDL2_image: prebuilt-x64/SDL2_image-2.0.5/lib/x64/SDL2_image.dll
      DLL for SDL2_mixer: prebuilt-x64/SDL2_mixer-2.6.2/lib/x64/SDL2_mixer.dll
      DLL for portmidi: prebuilt-x64/lib/portmidi.dll
      Path for FREETYPE: prebuilt-x64
      ...Library directory for FREETYPE: prebuilt-x64/lib
      ...Include directory for FREETYPE: prebuilt-x64/include
      Path for PNG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      Path for JPEG not found.
      ...Found include dir but no library dir in prebuilt-x64.
      DLL for freetype: prebuilt-x64/lib/freetype.dll
      DLL for png: prebuilt-x64/SDL2_image-2.0.5/lib/x64/libpng16-16.dll

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      Traceback (most recent call last):
        File "C:\Users\Name\AppData\Local\Programs\Python\Python312-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Name\AppData\Local\Programs\Python\Python312-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Name\AppData\Local\Programs\Python\Python312-arm64\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Name\AppData\Local\Temp\pip-build-env-fh7wftrg\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Name\AppData\Local\Temp\pip-build-env-fh7wftrg\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Name\AppData\Local\Temp\pip-build-env-fh7wftrg\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Name\AppData\Local\Temp\pip-build-env-fh7wftrg\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 409, in <module>
        File "C:\Users\Name\AppData\Local\Temp\pip-install-a1jrpqae\pygame_b44d42e63a284ec6ba8a48cbf92b35a9\buildconfig\config.py", line 231, in main
          deps = CFG.main(**kwds, auto_config=auto)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Name\AppData\Local\Temp\pip-install-a1jrpqae\pygame_b44d42e63a284ec6ba8a48cbf92b35a9\buildconfig\config_win.py", line 493, in main
          return setup_prebuilt_sdl2(prebuilt_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Name\AppData\Local\Temp\pip-install-a1jrpqae\pygame_b44d42e63a284ec6ba8a48cbf92b35a9\buildconfig\config_win.py", line 453, in setup_prebuilt_sdl2
          DEPS.configure()
        File "C:\Users\Name\AppData\Local\Temp\pip-install-a1jrpqae\pygame_b44d42e63a284ec6ba8a48cbf92b35a9\buildconfig\config_win.py", line 336, in configure
          from . import vstools
        File "C:\Users\Name\AppData\Local\Temp\pip-install-a1jrpqae\pygame_b44d42e63a284ec6ba8a48cbf92b35a9\buildconfig\vstools.py", line 8, in <module>
          compiler.initialize()
        File "C:\Users\Name\AppData\Local\Temp\pip-build-env-fh7wftrg\overlay\Lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 372, in initialize
          raise DistutilsPlatformError(f"--plat-name must be one of {ok_plats}")
      distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64')
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
system:
Windows 11 ARM (not preview build)
I am using a VM to actually make this work.

**Comment by quasar098** [comment]
do not build wheel

the executable was made using pyinstaller

**Comment by HHonzik** [comment]
>    Path for JPEG not found.
>   ...Found include dir but no library dir in prebuilt-x64.

>   distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64')

This seems to because binaries for ARM don't exist and everything trying to install X86 binaries which don't work on ARM (this is like starting a phone app on a PC, the PC doesn't understand it).

**Comment by quasar098** [comment]
just dont build a wheel,

use pyinstaller or run it from source
